# Generated by Django 4.0.1 on 2022-01-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='tittle',
            field=models.CharField(max_length=100, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='type',
            name='tittle',
            field=models.CharField(max_length=100, verbose_name='Тип задачи'),
        ),
    ]
